# Generated by Django 3.1.1 on 2020-10-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valid_Rog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthdate',
            field=models.DateTimeField(),
        ),
    ]
